import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import { PaletteProvider } from "@/components/PaletteProvider";
import PageTransition from "@/components/PageTransition";
import { LanguageProvider } from "@/lib/i18n/language-context";
import TopLeftControls from "@/components/TopLeftControls";

const rubik = Rubik({ subsets: ["hebrew", "latin"], variable: "--font-hebrew" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" suppressHydrationWarning className="dark">
      <body className={`${rubik.variable} antialiased`}>
        <LanguageProvider>
          <ThemeProvider>
            <PaletteProvider>
              <TopLeftControls />
        {/* Layout with sidebar on the right (RTL). Sidebar writes --sidebar-width
          to :root; the container uses that variable on large screens to avoid
          being covered by the fixed sidebar. */}
        <Sidebar />
        <div className="app-with-sidebar min-h-dvh flex flex-col">
                <main className="flex-1">
                  <PageTransition>{children}</PageTransition>
                </main>
                <Footer />
              </div>
            </PaletteProvider>
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
